In [4]:
import numpy as np

## 創建一個0到9的array
x = np.arange (10)
print('Save: ', x)

## 保存成npy檔
np.save('numpy_sample.npy', x)

## 不特別設定副檔名,會自動存成npy檔
np.save('numpy_samplel.npy', x)

## #npy
y = np.load('numpy_sample.npy')
print('Load: ', y)

Save:  [0 1 2 3 4 5 6 7 8 9]
Load:  [0 1 2 3 4 5 6 7 8 9]


In [6]:
## 查看一下npy裡面的內容
!type numpy_sample.npy

�NUMPYv{'descr': '<i4', 'fortran_order': False, 'shape': (10,), }                                                           
	


In [7]:
import numpy as np

x= np.arange(0, 10)

y = np.cos(x)

z = np.array([[2,4,6], [3,5,8]])

## 將多個array保存為npz
## y使用了關鍵字引數 cos_array,也就是之後會透過這個指定的關鍵字獲取y值
np.savez ('multiple_array.npz', x, z, cos_array = y)

## 載入npz檔
a = np.load('multiple_array.npz')

## 顯示所有array的名稱
print('Array Name: ', a.files)

## 直接print載回的檔案
print (a)

print('Array x: ', a['arr_0'])
print('Array y: ', a['cos_array'])
print('Array z: ', a['arr_1'])

Array Name:  ['cos_array', 'arr_0', 'arr_1']
Array x:  [0 1 2 3 4 5 6 7 8 9]
Array y:  [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]
Array z:  [[2 4 6]
 [3 5 8]]


In [8]:
!type multiple_array.npz

PK!|菹��
cos_array.npy���NUMPYv{'descr': '<f8', 'fortran_order': False, 'shape': (10,), }                                                           
�?��(J�?rSW&Ｌ諜���殷螟$�串靽愃kp�'�?�"x	溯�? ����?�/c蕪�聶k戌�'篻PK!nE-儘�	arr_0.npy���NUMPYv{'descr': '<i4', 'fortran_order': False, 'shape': (10,), }                                                           
	PK!�<
���	arr_1.npy���NUMPYv{'descr': '<i4', 'fortran_order': False, 'shape': (2, 3), }                                                          
PK!|菹��
�cos_array.npyPK!nE-儘�	�arr_0.npyPK!�<
���	��arr_1.npyPK��


In [14]:
import numpy as np

x = np.arange(10)
print('Save Text: ', x)

##存成txt檔
np.savetxt('example.txt',x)

##載入txt檔
y = np.loadtxt('example.txt')

print('Load Text: ', y)

Save Text:  [0 1 2 3 4 5 6 7 8 9]
Load Text:  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [24]:
import numpy as np

x = np.arange(0, 20).reshape(5, 4)
print('Original array:')
print (x)

## 存成浮點數array,並以宣漢賊畢
np.savetxt('example1.txt', x, fmt="%f", delimiter = "!")

## 載入text檔
y = np.loadtxt('example1.txt', delimiter = "!")
print('Load Text: ')
print (y)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Load Text: 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]


In [25]:
!type example.txt

0.000000000000000000e+00
1.000000000000000000e+00
2.000000000000000000e+00
3.000000000000000000e+00
4.000000000000000000e+00
5.000000000000000000e+00
6.000000000000000000e+00
7.000000000000000000e+00
8.000000000000000000e+00
9.000000000000000000e+00


In [ ]:
! examplel.txt